- Paths:
    directory: "/home/juanandres/Desktop/BOWPI/deployment-course/notebooks/dmlm-research-and-production/Assignments/Section-04/Procedural-Programming/Assignment/"
    data_filename: "titanic"
    data_extension: ".npy"
    output_scaler_path: "scaler.pkl"
    output_model_path: "logit.pkl"
- Parameters:
    imputation_dict:
      age: 28.0
      fare: 14.4542
    frequent_labels:
        sex: ['female', 'male']
        cabin: ['C', 'Missing']
        embarked: ['C','Q','S']
        title: ['Miss','Mr','Mrs']
    dummy_variables: ['sex_male', 'cabin_Missing', 'cabin_Rare', 'embarked_Q','embarked_Rare', 'embarked_S', 'title_Mr', 'title_Mrs','title_Rare']
- Feature_Groups:
    data_columns: ['pclass','survived','sex','age','sibsp','parch','fare','cabin','embarked','title']
    target: "survived"
    categorical_vars: ['sex','cabin','embarked','title']
    numerical_to_impute: ['age','fare']
